package GUI;

/**
 * GUI implementation for the Library page. Users can view their
 * current library by clicking on the button on the sidebar. All
 * library elements will be shown as a list under the library header.
 *
 * @author Brandon
 */
public class GUI_Library extends javax.swing.JFrame {
    private javax.swing.JButton addMediaButton;
    private javax.swing.JList<String> elementsInLibrary;
    private javax.swing.JLabel header;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton libraryPageButton;
    private javax.swing.JDesktopPane mainPane;
    private javax.swing.JLabel pageTitle;
    private javax.swing.JButton rateMediaButton;
    private javax.swing.JButton redoButton;
    private javax.swing.JButton removeMediaButton;
    private javax.swing.JButton searchPageButton;
    private javax.swing.JPanel sidebar;
    private javax.swing.JButton signOutButton;
    private javax.swing.JButton undoButton;

    /**
     * Creates new form GUI_Library
     */
    public GUI_Library() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {
        mainPane = new javax.swing.JDesktopPane();
        pageTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        elementsInLibrary = new javax.swing.JList<>();
        sidebar = new javax.swing.JPanel();
        header = new javax.swing.JLabel();
        searchPageButton = new javax.swing.JButton();
        libraryPageButton = new javax.swing.JButton();
        signOutButton = new javax.swing.JButton();
        undoButton = new javax.swing.JButton();
        redoButton = new javax.swing.JButton();
        addMediaButton = new javax.swing.JButton();
        removeMediaButton = new javax.swing.JButton();
        rateMediaButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPane.setBackground(new java.awt.Color(24, 24, 24));

        pageTitle.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        pageTitle.setForeground(new java.awt.Color(255, 255, 255));
        pageTitle.setText("Library");

        elementsInLibrary.setBackground(new java.awt.Color(24, 24, 24));
        elementsInLibrary.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        elementsInLibrary.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(elementsInLibrary);

        mainPane.setLayer(pageTitle, javax.swing.JLayeredPane.DEFAULT_LAYER);
        mainPane.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout mainPaneLayout = new javax.swing.GroupLayout(mainPane);
        mainPane.setLayout(mainPaneLayout);
        mainPaneLayout.setHorizontalGroup(
                mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(mainPaneLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(mainPaneLayout.createSequentialGroup()
                                                .addComponent(pageTitle)
                                                .addGap(0, 569, Short.MAX_VALUE))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addContainerGap())
        );
        mainPaneLayout.setVerticalGroup(
                mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(mainPaneLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(pageTitle)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
                                .addContainerGap())
        );

        sidebar.setBackground(new java.awt.Color(18, 18, 18));

        header.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        header.setForeground(new java.awt.Color(255, 255, 255));
        header.setText("Library");

        searchPageButton.setBackground(new java.awt.Color(24, 24, 24));
        searchPageButton.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        searchPageButton.setForeground(new java.awt.Color(255, 255, 255));
        searchPageButton.setText("Search");
        searchPageButton.setToolTipText("");
        searchPageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchPageButtonActionPerformed(evt);
            }
        });

        libraryPageButton.setBackground(new java.awt.Color(255, 255, 255));
        libraryPageButton.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        libraryPageButton.setForeground(new java.awt.Color(24, 24, 24));
        libraryPageButton.setText("Your Library");
        libraryPageButton.setToolTipText("");
        libraryPageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                libraryPageButtonActionPerformed(evt);
            }
        });

        signOutButton.setBackground(new java.awt.Color(24, 24, 24));
        signOutButton.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        signOutButton.setForeground(new java.awt.Color(255, 255, 255));
        signOutButton.setText("Sign Out");
        signOutButton.setToolTipText("");
        signOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signOutButtonActionPerformed(evt);
            }
        });

        undoButton.setBackground(new java.awt.Color(18, 18, 18));
        undoButton.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        undoButton.setForeground(new java.awt.Color(255, 255, 255));
        undoButton.setText("Undo");
        undoButton.setToolTipText("");
        undoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undoButtonActionPerformed(evt);
            }
        });

        redoButton.setBackground(new java.awt.Color(18, 18, 18));
        redoButton.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        redoButton.setForeground(new java.awt.Color(255, 255, 255));
        redoButton.setText("Redo");
        redoButton.setToolTipText("");
        redoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redoButtonActionPerformed(evt);
            }
        });

        addMediaButton.setBackground(new java.awt.Color(24, 24, 24));
        addMediaButton.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        addMediaButton.setForeground(new java.awt.Color(255, 255, 255));
        addMediaButton.setText("Add Media");
        addMediaButton.setToolTipText("");
        addMediaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMediaButtonActionPerformed(evt);
            }
        });

        removeMediaButton.setBackground(new java.awt.Color(24, 24, 24));
        removeMediaButton.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        removeMediaButton.setForeground(new java.awt.Color(255, 255, 255));
        removeMediaButton.setText("Remove Media");
        removeMediaButton.setToolTipText("");
        removeMediaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeMediaButtonActionPerformed(evt);
            }
        });

        rateMediaButton.setBackground(new java.awt.Color(24, 24, 24));
        rateMediaButton.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        rateMediaButton.setForeground(new java.awt.Color(255, 255, 255));
        rateMediaButton.setText("Rate Media");
        rateMediaButton.setToolTipText("");
        rateMediaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rateMediaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidebarLayout = new javax.swing.GroupLayout(sidebar);
        sidebar.setLayout(sidebarLayout);
        sidebarLayout.setHorizontalGroup(
                sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(sidebarLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(searchPageButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(libraryPageButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                                        .addComponent(signOutButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidebarLayout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(redoButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(undoButton))
                                        .addComponent(addMediaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(removeMediaButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(rateMediaButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        sidebarLayout.setVerticalGroup(
                sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(sidebarLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(header)
                                .addGap(18, 18, 18)
                                .addComponent(searchPageButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(libraryPageButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addMediaButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(removeMediaButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rateMediaButton)
                                .addGap(18, 18, 18)
                                .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(undoButton)
                                        .addComponent(redoButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(signOutButton)
                                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mainPane))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(sidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mainPane)
        );

        pack();
    }

    private void searchPageButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        this.setVisible(false);
        new GUI_Search().setVisible(true);
    }

    private void libraryPageButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // DO NOTHING (ALREADY IN LIBRARY, DON'T NEED TO RECREATE INSTANCE OF PAGE)
    }

    private void signOutButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        this.setVisible(false);
        System.exit(0);
    }

    private void addMediaButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        new GUI_AddMedia().setVisible(true);
    }

    private void removeMediaButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        new GUI_RemoveMedia().setVisible(true);
    }

    private void rateMediaButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        new GUI_RateMedia().setVisible(true);
    }

    private void undoButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

    }

    private void redoButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Library.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Library.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Library.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Library.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Library().setVisible(true);
            }
        });
    }
}