package GUI;

import ObjectModules.LibraryElement;

import java.text.ParseException;
import java.util.ArrayList;
import java.util.Arrays;

/**
 * GUI implementation for the Search page. Users can search for media
 * using the provided search bar and search type list. After clicking
 * search, a list of results will populate in the search results list
 * pane, slightly below the actual search query.
 *
 * @author Brandon Montijo
 */
public class GUI_Search extends javax.swing.JFrame {
    private javax.swing.JButton actionSearchButton;
    private javax.swing.JLabel header;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton libraryPageButton;
    private javax.swing.JDesktopPane mainPane;
    private javax.swing.JLabel pageTitle;
    private javax.swing.JButton redoButton;
    private javax.swing.JButton searchPageButton;
    private javax.swing.JList<String> searchResultsList;
    private javax.swing.JComboBox<String> searchSelector;
    private javax.swing.JTextField searchTextBox;
    private javax.swing.JPanel sidebar;
    private javax.swing.JButton signOutButton;
    private javax.swing.JButton undoButton;

    /**
     * Creates new form GUI_Search
     */
    public GUI_Search() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {
        mainPane = new javax.swing.JDesktopPane();
        pageTitle = new javax.swing.JLabel();
        searchTextBox = new javax.swing.JTextField();
        actionSearchButton = new javax.swing.JButton();
        searchSelector = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        searchResultsList = new javax.swing.JList<>();
        sidebar = new javax.swing.JPanel();
        header = new javax.swing.JLabel();
        searchPageButton = new javax.swing.JButton();
        libraryPageButton = new javax.swing.JButton();
        signOutButton = new javax.swing.JButton();
        undoButton = new javax.swing.JButton();
        redoButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPane.setBackground(new java.awt.Color(24, 24, 24));
        mainPane.setFont(new java.awt.Font("Tw Cen MT", 0, 11)); // NOI18N

        pageTitle.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        pageTitle.setForeground(new java.awt.Color(255, 255, 255));
        pageTitle.setText("Search");

        searchTextBox.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        searchTextBox.setText("Search for Songs, Releases, or Artists");
        searchTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTextBoxActionPerformed(evt);
            }
        });

        actionSearchButton.setBackground(new java.awt.Color(24, 24, 24));
        actionSearchButton.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        actionSearchButton.setForeground(new java.awt.Color(255, 255, 255));
        actionSearchButton.setText("Search");
        actionSearchButton.setToolTipText("");
        actionSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    actionSearchButtonActionPerformed(evt);
                } catch (ParseException e) {
                    e.printStackTrace();
                }
            }
        });

        searchSelector.setBackground(new java.awt.Color(24, 24, 24));
        searchSelector.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        searchSelector.setForeground(new java.awt.Color(255, 255, 255));
        searchSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Song", "Release", "Artist" }));

        searchResultsList.setBackground(new java.awt.Color(24, 24, 24));
        searchResultsList.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        searchResultsList.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(searchResultsList);

        mainPane.setLayer(pageTitle, javax.swing.JLayeredPane.DEFAULT_LAYER);
        mainPane.setLayer(searchTextBox, javax.swing.JLayeredPane.DEFAULT_LAYER);
        mainPane.setLayer(actionSearchButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        mainPane.setLayer(searchSelector, javax.swing.JLayeredPane.DEFAULT_LAYER);
        mainPane.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout mainPaneLayout = new javax.swing.GroupLayout(mainPane);
        mainPane.setLayout(mainPaneLayout);
        mainPaneLayout.setHorizontalGroup(
                mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPaneLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jScrollPane1)
                                        .addGroup(mainPaneLayout.createSequentialGroup()
                                                .addComponent(pageTitle)
                                                .addGap(18, 18, 18)
                                                .addComponent(searchTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(searchSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                                                .addComponent(actionSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
        );
        mainPaneLayout.setVerticalGroup(
                mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(mainPaneLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(pageTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(searchTextBox)
                                                .addComponent(actionSearchButton)
                                                .addComponent(searchSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                                .addContainerGap())
        );

        sidebar.setBackground(new java.awt.Color(18, 18, 18));
        sidebar.setFont(new java.awt.Font("Tw Cen MT", 0, 11)); // NOI18N

        header.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        header.setForeground(new java.awt.Color(255, 255, 255));
        header.setText("Search");

        searchPageButton.setBackground(new java.awt.Color(255, 255, 255));
        searchPageButton.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        searchPageButton.setForeground(new java.awt.Color(18, 18, 18));
        searchPageButton.setText("Search");
        searchPageButton.setToolTipText("");
        searchPageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchPageButtonActionPerformed(evt);
            }
        });

        libraryPageButton.setBackground(new java.awt.Color(18, 18, 18));
        libraryPageButton.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        libraryPageButton.setForeground(new java.awt.Color(255, 255, 255));
        libraryPageButton.setText("Your Library");
        libraryPageButton.setToolTipText("");
        libraryPageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                libraryPageButtonActionPerformed(evt);
            }
        });

        signOutButton.setBackground(new java.awt.Color(24, 24, 24));
        signOutButton.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        signOutButton.setForeground(new java.awt.Color(255, 255, 255));
        signOutButton.setText("Sign Out");
        signOutButton.setToolTipText("");
        signOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signOutButtonActionPerformed(evt);
            }
        });

        undoButton.setBackground(new java.awt.Color(18, 18, 18));
        undoButton.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        undoButton.setForeground(new java.awt.Color(255, 255, 255));
        undoButton.setText("Undo");
        undoButton.setToolTipText("");
        undoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undoButtonActionPerformed(evt);
            }
        });

        redoButton.setBackground(new java.awt.Color(18, 18, 18));
        redoButton.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        redoButton.setForeground(new java.awt.Color(255, 255, 255));
        redoButton.setText("Redo");
        redoButton.setToolTipText("");
        redoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidebarLayout = new javax.swing.GroupLayout(sidebar);
        sidebar.setLayout(sidebarLayout);
        sidebarLayout.setHorizontalGroup(
                sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(sidebarLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(searchPageButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(libraryPageButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                                        .addComponent(signOutButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidebarLayout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(redoButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(undoButton)))
                                .addContainerGap())
        );
        sidebarLayout.setVerticalGroup(
                sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(sidebarLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(header)
                                .addGap(18, 18, 18)
                                .addComponent(searchPageButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(libraryPageButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(undoButton)
                                        .addComponent(redoButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(signOutButton)
                                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mainPane))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(sidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mainPane)
        );

        pack();
    }

    private void searchPageButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        this.setVisible(false);
        new GUI_Search().setVisible(true);
    }

    private void libraryPageButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        this.setVisible(false);
        GUI_Handler.libraryPage.setVisible(true);
    }

    private void signOutButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        this.setVisible(false);
        System.exit(0);
    }

    private void actionSearchButtonActionPerformed(java.awt.event.ActionEvent evt) throws ParseException {
        // TODO add your handling code here:
        StringBuilder cmd = new StringBuilder();
        cmd.append("search;");
        cmd.append(searchSelector.getSelectedItem().toString().toLowerCase() + ";");
        cmd.append(searchTextBox.getText() + ";");
        String[] results = GUI_Handler.requestHandler.handleRequest(cmd.toString()).getResponse().split("\n");
        searchResultsList.setListData(Arrays.copyOfRange(results, 1, results.length));
    }

    private void searchTextBoxActionPerformed(java.awt.event.ActionEvent evt) { }

    private void undoButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // IMPLEMENTATION NOT APART OF R1
    }

    private void redoButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // IMPLEMENTATION NOT APART OF R1
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Search().setVisible(true);
            }
        });
    }
}
